### ISSUE TITLE
add StockCategory to kayord db

### ISSUE THREAD

**Issue by jakers07** [kayordDX/pos#5]
add StockCategory to kayord db with foreign key in "Stock" table

Differentiate between various stock categories.  Needed during stock take and for MI purposes

CREATE TABLE public."StockCategory"
(
    "Id" integer STORAGE PLAIN NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" text,
    PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public."StockCategory"
    OWNER to kayord;

ALTER TABLE IF EXISTS public."Stock"
    ADD COLUMN "StockCategoryId" integer;
ALTER TABLE IF EXISTS public."Stock"
    ADD CONSTRAINT "FK_StockCategory_StockCategoryId" FOREIGN KEY ("StockCategoryId")
    REFERENCES public."StockCategory" ("Id") MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

**Comment by jacokok** [comment]
Stock category table has been added.
