### ISSUE TITLE
Halo payment not reflecting on bill

### ISSUE THREAD

**Issue by jakers07** [kayordDX/pos#6]
Halo payment is successful but not reflecting on bill

HaloReference.Id= 'acc059a3-8f81-40de-8e08-65f5bfe11135'

![image](https://github.com/user-attachments/assets/d6e6f060-49b4-44dd-ac2e-27b082950044)

![image](https://github.com/user-attachments/assets/ed414932-d4d5-4239-a58e-fdc27b0a0790)

**Comment by jacokok** [comment]
Can confirm this was successful  with 542 as amount.

**Comment by jacokok** [comment]
![image](https://github.com/user-attachments/assets/eef8950b-5dcf-4a6e-b248-e73fc57f85b2)

We now have a new option on front end hidden under show detail switch.
This will recheck the status of all halo payments in case the back end checker missed it and they did not return to kayord after payment.

The back-end number of checks has been increased and this should rarely be required.
